name : music


on:
    schedule:
      - cron: "0 */6 * * *"
    push:
      branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ secrets.TOKEN }}
       - name: Set up Python 3.9
         uses: actions/setup-python@v2.2.2
         with:
           python-version: 3.9

       - name: init
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.NAME }}
           git config --global user.email ${{ secrets.MAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.NAME }}:${{ secrets.TOKEN }}@github.com" > ~/.git-credentials
       - name: cloning repo and install
         continue-on-error: true
         run: |
           git clone https://${{ secrets.NAME }}:${{ secrets.TOKEN }}@github.com/railwaysama/vcbot discord && cd discord && pip3 install -r requirements.txt
           pwd
       - name: Running
         timeout-minutes: 350
         continue-on-error: true
         run: |
           sudo apt -qq update && sudo apt -qq install -y --no-install-recommends ffmpeg neofetch
           pwd
           cd discord
           python3 main.py
